version: "3.9"

services:

  redis-pubsub:
    image: redis/redis-stack-server:latest
    container_name: redis-pubsub
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly no
      --protected-mode no
      --loadmodule /opt/redis-stack/lib/rejson.so
      --loadmodule /opt/redis-stack/lib/redisearch.so
    restart: unless-stopped

  redis-7000:
    image: redis/redis-stack-server:latest
    container_name: redis-7000
    command: >
      redis-server
      --cluster-enabled yes
      --port 7000
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --protected-mode no
      --loadmodule /opt/redis-stack/lib/rejson.so
    ports:
      - "7000:7000"
    networks:
      - redis-cluster

  redis-7001:
    image: redis/redis-stack-server:latest
    container_name: redis-7001
    command: >
      redis-server
      --cluster-enabled yes
      --port 7001
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --protected-mode no
      --loadmodule /opt/redis-stack/lib/rejson.so
    ports:
      - "7001:7001"
    networks:
      - redis-cluster

  redis-7002:
    image: redis/redis-stack-server:latest
    container_name: redis-7002
    command: >
      redis-server
      --cluster-enabled yes
      --port 7002
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --protected-mode no
      --loadmodule /opt/redis-stack/lib/rejson.so
    ports:
      - "7002:7002"
    networks:
      - redis-cluster

  redis-7003:
    image: redis/redis-stack-server:latest
    container_name: redis-7003
    command: >
      redis-server
      --cluster-enabled yes
      --port 7003
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --protected-mode no
      --loadmodule /opt/redis-stack/lib/rejson.so
    ports:
      - "7003:7003"
    networks:
      - redis-cluster

  redis-7004:
    image: redis/redis-stack-server:latest
    container_name: redis-7004
    command: >
      redis-server
      --cluster-enabled yes
      --port 7004
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --protected-mode no
      --loadmodule /opt/redis-stack/lib/rejson.so
    ports:
      - "7004:7004"
    networks:
      - redis-cluster

  redis-7005:
    image: redis/redis-stack-server:latest
    container_name: redis-7005
    command: >
      redis-server
      --cluster-enabled yes
      --port 7005
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --protected-mode no
      --loadmodule /opt/redis-stack/lib/rejson.so
    ports:
      - "7005:7005"
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge


# docker exec -it redis-7000 redis-cli --cluster create \
#   redis-7000:7000 \
#   redis-7001:7001 \
#   redis-7002:7002 \
#   redis-7003:7003 \
#   redis-7004:7004 \
#   redis-7005:7005 \
#   --cluster-replicas 1
