
services:
  redis-7000:
    image: redis/redis-stack-server:latest
    container_name: redis-7000
    command: ["redis-server", "--cluster-enabled", "yes", "--port", "7000", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes", "--protected-mode", "no", "--loadmodule", "/opt/redis-stack/lib/rejson.so",]
    ports:
      - "7000:7000"

  redis-7001:
    image: redis/redis-stack-server:latest
    container_name: redis-7001
    command: ["redis-server", "--cluster-enabled", "yes", "--port", "7001", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes", "--protected-mode", "no", "--loadmodule", "/opt/redis-stack/lib/rejson.so",]
    ports:
      - "7001:7001"

  redis-7002:
    image: redis/redis-stack-server:latest
    container_name: redis-7002
    command: ["redis-server", "--cluster-enabled", "yes", "--port", "7002", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes", "--protected-mode", "no", "--loadmodule", "/opt/redis-stack/lib/rejson.so",]
    ports:
      - "7002:7002"

# docker compose up -d
# docker exec -it redis-7000 redis-cli --cluster create redis-7000:7000 redis-7001:7001 redis-7002:7002 --cluster-replicas 0
# docker exec -it redis-7002 redis-cli -p 7002 PUBSUB CHANNELS